name: Check new version

on:
  workflow_dispatch:

jobs:
  check_version:
    uses: mpvkit/BuildShared/.github/workflows/check_version.yml@main
    secrets: inherit
    with:
      repository: 'uavs3/uavs3d'
      library: 'libuavs3d'
